// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SupportTools.Server.Data;

#nullable disable

namespace SupportTools.Server.Migrations
{
    [DbContext(typeof(SupportToolsDbContext))]
    [Migration("20251110153130_InitApotheekAtcRelatie")]
    partial class InitApotheekAtcRelatie
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ATCCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ATCCodes");
                });

            modelBuilder.Entity("Apotheek", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AGB")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MosadexId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Apotheken");
                });

            modelBuilder.Entity("ApotheekATC", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ATCCodeId")
                        .HasColumnType("int");

                    b.Property<int>("ApotheekId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ATCCodeId");

                    b.HasIndex("ApotheekId");

                    b.ToTable("ApotheekATCs");
                });

            modelBuilder.Entity("ApotheekATC", b =>
                {
                    b.HasOne("ATCCode", "ATCCode")
                        .WithMany("ApotheekATCs")
                        .HasForeignKey("ATCCodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Apotheek", "Apotheek")
                        .WithMany("ApotheekATCs")
                        .HasForeignKey("ApotheekId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ATCCode");

                    b.Navigation("Apotheek");
                });

            modelBuilder.Entity("ATCCode", b =>
                {
                    b.Navigation("ApotheekATCs");
                });

            modelBuilder.Entity("Apotheek", b =>
                {
                    b.Navigation("ApotheekATCs");
                });
#pragma warning restore 612, 618
        }
    }
}
